# Apache -> PHP-FPM (port 9000)

Listen 80

## Modules nécessaires:
#
LoadModule mpm_event_module modules/mod_mpm_event.so
# module : mas2oul 3ala permissions
LoadModule authz_core_module modules/mod_authz_core.so
# module : e5ali el apache yefhem 'index.php' / 'index.html' :
LoadModule dir_module modules/mod_dir.so
# module : bach ya3ref anwa3 el files ('.php' | '.html'| ...) :
LoadModule mime_module modules/mod_mime.so

## modules PROXY : ** bach apache ya7ki em3a el PHP-FPM 3aber el FastCGI**
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

## modules logd :
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so

# utilisateur Apache
User www-data
Group www-data

ServerName localhost

# Dossier racine du site web
DocumentRoot "/var/www/html"
<Directory "/var/www/html">
	AllowOverride All
	Require all granted
	DirectoryIndex index.php index.html
</Directory>

# transmettre tous les fichiers .php vers PHP-FPM
<FilesMatch "\.php$">
	SetHandler "proxy:fcgi://phpfpm:9000" 
</FilesMatch>
# port 9000 => port par defaut de PHP-FPM
# 'phpfpm' => nom du service dans docker-compose.yml 

# Types MIME => anwa3 el files standard
TypesConfig conf/mime.types

# Logs = docker logs
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common
